<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $courses = [
            // Web Development
            [
                'title' => 'معسكر تدريب تطوير الويب للمبتدئين',
                'description' => 'تعلم أساسيات تطوير الويب.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 300,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'تقنيات تطوير الويب المتوسطة',
                'description' => 'عزز مهاراتك في تطوير الويب باستخدام تقنيات متوسطة.',
                'instructor_id' => 1,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'أفضل ممارسات تطوير الويب المتقدمة',
                'description' => 'اتقن أفضل ممارسات تطوير الويب المتقدمة.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 550,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // Data Science
            [
                'title' => 'أسس علم البيانات للمبتدئين',
                'description' => 'تعلم أساسيات علم البيانات.',
                'instructor_id' => 2,
                'level' => 'مبتدئ',
                'price' => 320,
                'duration' => 150,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'علم البيانات المتوسط باستخدام بايثون',
                'description' => 'قم بتطوير مهارات علم البيانات المتوسطة باستخدام بايثون.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 420,
                'duration' => 200,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'تقنيات علم البيانات المتقدمة',
                'description' => 'استكشف التقنيات المتقدمة في علم البيانات.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 600,
                'duration' => 220,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // Artificial Intelligence
            [
                'title' => 'أساسيات الذكاء الاصطناعي للمبتدئين',
                'description' => 'فهم أساسيات الذكاء الاصطناعي.',
                'instructor_id' => 4,
                'level' => 'مبتدئ',
                'price' => 330,
                'duration' => 130,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'تطبيقات الذكاء الاصطناعي المتوسطة',
                'description' => 'تعلم كيفية تطبيق مفاهيم الذكاء الاصطناعي في السيناريوهات الواقعية.',
                'instructor_id' => 4,
                'level' => 'متوسط',
                'price' => 440,
                'duration' => 190,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'أنظمة الذكاء الاصطناعي المتقدمة',
                'description' => 'تعمق في أنظمة الذكاء الاصطناعي المتقدمة والهندسات.',
                'instructor_id' => 5,
                'level' => 'متقدم',
                'price' => 650,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // Machine Learning
            [
                'title' => 'مفاهيم تعلم الآلة للمبتدئين',
                'description' => 'تعلم أساسيات تعلم الآلة.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 310,
                'duration' => 140,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'تعلم الآلة المتوسطة باستخدام R',
                'description' => 'تطوير مهارات تعلم الآلة المتوسطة باستخدام R.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 430,
                'duration' => 210,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'خوارزميات تعلم الآلة المتقدمة',
                'description' => 'استكشاف خوارزميات متقدمة في تعلم الآلة.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 590,
                'duration' => 260,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // الأمن السيبراني
            [
                'title' => 'أساسيات الأمن السيبراني للمبتدئين',
                'description' => 'تعلم أساسيات الأمن السيبراني.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 290,
                'duration' => 130,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'تهديدات الأمن السيبراني المتوسطة',
                'description' => 'فهم تهديدات الأمن السيبراني المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 390,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'تقنيات الدفاع في الأمن السيبراني المتقدم',
                'description' => 'تعلم تقنيات الدفاع المتقدمة في الأمن السيبراني.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 620,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

// تطوير البرمجيات
            [
                'title' => 'أساسيات تطوير البرمجيات للمبتدئين',
                'description' => 'تعلم أساسيات تطوير البرمجيات.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 300,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'تقنيات تطوير البرمجيات المتوسطة',
                'description' => 'استكشاف تقنيات تطوير البرمجيات المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 450,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'مشاريع تطوير البرمجيات المتقدمة',
                'description' => 'العمل على مشاريع تطوير البرمجيات المتقدمة.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 600,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

// تطوير الألعاب
            [
                'title' => 'أساسيات تطوير الألعاب للمبتدئين',
                'description' => 'تعلم أساسيات تطوير الألعاب.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 350,
                'duration' => 150,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'تقنيات تطوير الألعاب المتوسطة',
                'description' => 'استكشاف تقنيات تطوير الألعاب المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'استراتيجيات تطوير الألعاب المتقدمة',
                'description' => 'تعلم استراتيجيات متقدمة في تطوير الألعاب.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 650,
                'duration' => 300,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],
            // Mobile Development
            [
                'title' => 'مبتدئ أساسيات تطوير التطبيقات المحمولة',
                'description' => 'تعلم أساسيات تطوير التطبيقات المحمولة.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 320,
                'duration' => 130,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'متوسط تطوير تطبيقات المحمول',
                'description' => 'غص في عمق تطوير تطبيقات المحمول.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 380,
                'duration' => 170,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'متقدم تقنيات تطوير التطبيقات المحمولة',
                'description' => 'أتقن تقنيات تطوير التطبيقات المحمولة المتقدمة.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 700,
                'duration' => 250,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],
            
            // اختبار البرمجيات
            [
                'title' => 'مبتدئ أساسيات اختبار البرمجيات',
                'description' => 'تعلم أساسيات اختبار البرمجيات.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 280,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'متوسط تقنيات اختبار البرمجيات',
                'description' => 'استكشف التقنيات المتوسطة في اختبار البرمجيات.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'متقدم استراتيجيات اختبار البرمجيات',
                'description' => 'أتقن استراتيجيات اختبار البرمجيات المتقدمة.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 650,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],
            // الرياضيات
            [
                'title' => 'دورة الرياضيات للمبتدئين',
                'description' => 'تعلم أساسيات الرياضيات.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 300,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الرياضيات المتوسطة',
                'description' => 'استكشاف المفاهيم الرياضية المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الرياضيات المتقدمة',
                'description' => 'تعلم الرياضيات المتقدمة.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 600,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // الإحصاء والاحتمالات
            [
                'title' => 'دورة الإحصاء للمبتدئين',
                'description' => 'تعلم أساسيات الإحصاء.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 300,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الإحصاء المتوسطة',
                'description' => 'استكشاف مفاهيم الإحصاء المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الإحصاء المتقدمة',
                'description' => 'تعلم الإحصاء المتقدم.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 600,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // الفيزياء
            [
                'title' => 'دورة الفيزياء للمبتدئين',
                'description' => 'تعلم أساسيات الفيزياء.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 300,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الفيزياء المتوسطة',
                'description' => 'استكشاف مفاهيم الفيزياء المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الفيزياء المتقدمة',
                'description' => 'تعلم الفيزياء المتقدمة.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 600,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // الكيمياء
            [
                'title' => 'دورة الكيمياء للمبتدئين',
                'description' => 'تعلم أساسيات الكيمياء.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 300,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الكيمياء المتوسطة',
                'description' => 'استكشاف مفاهيم الكيمياء المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الكيمياء المتقدمة',
                'description' => 'تعلم الكيمياء المتقدمة.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 600,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // الهندسة الكهربائية
            [
                'title' => 'دورة الهندسة الكهربائية للمبتدئين',
                'description' => 'تعلم أساسيات الهندسة الكهربائية.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 300,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الهندسة الكهربائية المتوسطة',
                'description' => 'استكشاف مفاهيم الهندسة الكهربائية المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الهندسة الكهربائية المتقدمة',
                'description' => 'تعلم الهندسة الكهربائية المتقدمة.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 600,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // الطب والصحة
            [
                'title' => 'دورة الطب للمبتدئين',
                'description' => 'تعلم أساسيات الطب.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 300,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الطب المتوسطة',
                'description' => 'استكشاف مفاهيم الطب المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الطب المتقدمة',
                'description' => 'تعلم الطب المتقدم.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 600,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // اللغة والأدب
            [
                'title' => 'دورة اللغة للمبتدئين',
                'description' => 'تعلم أساسيات اللغة.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 300,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة اللغة المتوسطة',
                'description' => 'استكشاف مفاهيم اللغة المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة اللغة المتقدمة',
                'description' => 'تعلم اللغة المتقدمة.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 600,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // التاريخ
            [
                'title' => 'دورة التاريخ للمبتدئين',
                'description' => 'تعلم أساسيات التاريخ.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 300,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة التاريخ المتوسطة',
                'description' => 'استكشاف مفاهيم التاريخ المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة التاريخ المتقدمة',
                'description' => 'تعلم التاريخ المتقدم.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 600,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],

            // الفلسفة
            [
                'title' => 'دورة الفلسفة للمبتدئين',
                'description' => 'تعلم أساسيات الفلسفة.',
                'instructor_id' => 1,
                'level' => 'مبتدئ',
                'price' => 300,
                'duration' => 120,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الفلسفة المتوسطة',
                'description' => 'استكشاف مفاهيم الفلسفة المتوسطة.',
                'instructor_id' => 2,
                'level' => 'متوسط',
                'price' => 400,
                'duration' => 180,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 1,
            ],
            [
                'title' => 'دورة الفلسفة المتقدمة',
                'description' => 'تعلم الفلسفة المتقدمة.',
                'instructor_id' => 3,
                'level' => 'متقدم',
                'price' => 600,
                'duration' => 240,
                'image' => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
                'subscription_plan_id' => 2,
            ],
        ];

        // Now, create the courses in the database
        foreach ($courses as $course) {
            \App\Models\Course::create($course);
        }

    }
}
